version: '3.8'

services:
  postgres_master:
    container_name: postgres_master
    image: postgres:14.5
    restart: always
    volumes:
      - master-data:/var/lib/postgresql/data
      - ./init-script/master:/docker-entrypoint-initdb.d/
      - ./init-script/config/master/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./init-script/config/master/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  postgres_slave:
    container_name: postgres_slave
    image: postgres:14.5
    restart: always
    depends_on:
      - postgres_master
    volumes:
      - replica-data:/var/lib/postgresql/data
      - ./init-script/replica/entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
      - ./init-script/config/replica/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./init-script/config/replica/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=replica_password
    command:
      - "bash"
      - "/docker-entrypoint-initdb.d/entrypoint.sh"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  master-data:
  replica-data: