kafka:
  broker: "kafka:9092"
  topics:
    - "postgres_master.public.bookings"
    - "postgres_master.public.flights"
    - "postgres_master.public.tickets"

dwh:
  host: "postgres_dwh"
  port: 5432
  user: "postgres"
  password: "postgres_dwh"
  dbname: "dwh_detailed"